### ISSUE TITLE
Copy ERRORLOG.* to log folder for all SQL Server instances.

### ISSUE THREAD

**Issue by Malcolm-Stewart** [microsoft/CSS_SQL_Networking_Tools#27]
Enumerate all SQL Server instances and locate the ERRORLOG folder.
Create a log folder called ERRORLOG_<instancename> and copy all the ERRORLOG files into it.
Q. Do we need 32-bit SQL support or just assume all modern SQL Servers are 64-bit?

**Comment by dineubr** [comment]
I've just added a pull request to address this task.
For the moment we are not considering instances with 32-bit architecture.

**Comment by Malcolm-Stewart** [comment]
Added and fixed.
