### ISSUE TITLE
Some registry commands list an error

### ISSUE THREAD

**Issue by Malcolm-Stewart** [microsoft/CSS_SQL_Networking_Tools#33]
Specifically:

            reg delete HKLM\SYSTEM\CurrentControlSet\Control\LSA\NegoExtender\Parameters /v InfoLevel /f  2>&1 
            reg delete HKLM\SYSTEM\CurrentControlSet\Control\LSA\Pku2u\Parameters /v InfoLevel /f  2>&1
            reg delete HKLM\SYSTEM\CurrentControlSet\Control\LSA /v LspDbgInfoLevel /f  2>&1
            reg delete HKLM\SYSTEM\CurrentControlSet\Control\LSA /v LspDbgTraceOptions /f  2>&1

Keys are not found. Do we create them?
Need to investigate or just eat the exceptions - or log them better - see previous issue.

**Comment by dineubr** [comment]
I've just added a pull request to address this task.
The keys were missing in the Start process flow and because of that we were getting the error message once the Stop function was triggered.
