### ISSUE TITLE
SQLCHECK Write output to log file 

### ISSUE THREAD

**Issue by ClintWon** [microsoft/CSS_SQL_Networking_Tools#50]
Currently output is displayed to the screen and requires redirection to get it to file.
Customers are not always familiar with redirection and automatically creating the log file will save time.

**Comment by Omcsesz** [comment]
> Currently output is displayed to the screen and requires redirection to get it to file. Customers are not always familiar with redirection and automatically creating the log file will save time.

@ClintWon The redirection does not work on my computer, I get a zero sized log file. I use Win10, 64-bit.

**Comment by Malcolm-Stewart** [comment]
@Omcsesz Are you running the command prompt "As Administrator"?
Are you running cmd.exe or PowerShell?
What is your command-line?

**Comment by Omcsesz** [comment]
@Malcolm-Stewart I used cmd.exe. I found out that the problem was that I did not have rights to that folder (c:\temp)

**Comment by Malcolm-Stewart** [comment]
SQLCheck now writes to a log file in the same folder with the computer name and timestamp as part of the file name.
