### ISSUE TITLE
All tools

### ISSUE THREAD

**Issue by coraphise** [microsoft/CSS_SQL_Networking_Tools#58]
Can we start zipping tools without saving folder information in the zip file?  Customers and, worse, Engineers do not understand that unzipping to something like this:

C:\SQLTrace

Means they need to be in this instead:

C:\SQLTrace\SQLTrace

**Comment by Malcolm-Stewart** [comment]
It's an extra manual step but I am doing it.

**Comment by Malcolm-Stewart** [comment]
.
