### ISSUE TITLE
SQLCheck Provider and Driver TLS 1.2 Yes/No column may be wrong in some cases

### ISSUE THREAD

**Issue by ktgi** [microsoft/CSS_SQL_Networking_Tools#60]
Please check correctness of TLS 1.2 Yes/No for "SQLOLEDB" and "SQL Server" (supplied/updated with the operating system).
According to https://support.microsoft.com/en-us/topic/october-20-2020-kb4580390-os-build-17763-1554-preview-ac4799c9-838f-8665-a968-0f19b6cb1049 these providers support TLS 1.1 and 1.2:
"Adds support for the Transport Layer Security (TLS) 1.1 and 1.2 protocols when connecting to SQL Server using the data providers in Microsoft Data Access Components (MDAC)"
Tested with these providers from Windows 10 21H2 19044.2604 against SQL Server 2016 with extended event session sqlsni.trace:
SNISecurity Handshake Handshake succeeded. Protocol: TLS1.2
SQLCheck reports TLS 1.2 No:
Name                           Type    Version                    Supported   TLS 1.2
SQLOLEDB                   OLE DB  10.0.19041.2604  Deprecated  No 
SQL Server                   ODBC     10.0.19041.2604  Deprecated  No

**Comment by Malcolm-Stewart** [comment]
These drivers only support TLS 1.1/1.2 on Windows 2019 Nov/Dec 2020 security update. Anything earlier than that only supports TLS 1.0. No SQL 2016 versions or earlier Windows versions support 1.1/1.2 via this driver.
Equivalent Windows 10 versions also support TLS 1.1/1.2 with the driver.
The file actually updated is DBNETLIB.DLL, which both drivers rely on.
