### ISSUE TITLE
SQLCheck Feature Request

### ISSUE THREAD

**Issue by coraphise** [microsoft/CSS_SQL_Networking_Tools#61]
Can we add a column to the Cipher Suite section, probably for both Registry list and Policy list, that indicates which SSL/TLS versions a detected Cipher Suite can be used with?

**Comment by coraphise** [comment]
After further discussion, we should also expose the "Allowed by Strong Crypto" details as well.

**Comment by coraphise** [comment]
Also adding a notice / warning regarding the "_p###" Cipher Suites.

Older operating systems (version to be confirmed) require that we utilize Cipher Suites with the "_p###" format.

Newer operating systems understand these, but don't use them by default.

**Comment by Malcolm-Stewart** [comment]
Done.
