### ISSUE TITLE
SQLCheck not showing listener for a contained AG

### ISSUE THREAD

**Issue by SeanCowburnMSFT** [microsoft/CSS_SQL_Networking_Tools#63]
Tested on SQL 2022 Developer CU 3

--from the log
Always-On Servers:          WIN22SQL22N2, WIN22SQL22N1
Always-On Listeners:        AGDB2022
Availability Groups:        AGDB2022, ContainedAG

--from the DMVs
ag_name	        ag_listeiner_dns_name	        agl_port	        agl_config_string
AGDB2022	AGDB2022		                1433		('IP Address: 15.0.0.113')
ContainedAG	ContainedAG		                1434		('IP Address: 15.0.0.114')

AGDB2022 is a regular AG
ContainedAG as the name suggests is a contained AG

Possible cause is that the port for the listener is 1434. (?)

**Comment by Malcolm-Stewart** [comment]
We do not connect to the database server and run DMVs. This tool is meant to be run by a member of the Administrators group and not a SQL sysadmin. In some companies, these roles are mutually exclusive.
