### ISSUE TITLE
SQLBench Suggestion

### ISSUE THREAD

**Issue by jonreis** [microsoft/CSS_SQL_Networking_Tools#64]
First, thank you for providing this tool.

I made a small modification to the tool and on our systems it shows better results. In WriteBlobTest I changed the size to 100K from 16K which I think is more representative of a Large Binary Object and I also randomize the bytes. If you create a byte array, the array will contain all 0 which compresses very well and may hide performance issues especially if compression is turned on in the database.

        public void  WriteBlobTest(out double myBlobWrite)
        {
            const int size = 100 * 1024; // 100K was 16K
            byte[] numArray1 = new byte[size]; //crate byte array
            var random = new Random();
            random.NextBytes(numArray1); // randomize the array so compression doesn't come into play

**Comment by Malcolm-Stewart** [comment]
I think you mean SQLBench, not SQLCheck.

**Comment by jonreis** [comment]
@Malcolm-Stewart, yes sorry about that. I corrected it

**Comment by ClintWon** [comment]
Change completed.  Resolving issue.
