### ISSUE TITLE
SPN is on wrong account

### ISSUE THREAD

**Issue by garfield7791** [microsoft/CSS_SQL_Networking_Tools#81]
The SQL CHECK Tool reports "SPN is on the wrong account" if the SQL Server Service is set to Log On as <svc-user>@<domain>
If the SQL Server Service is set to Lon On as <domain>\<service-user> it reports that the SPN is "Okay".
Anyone can explain this behaviour?
Thanks
Adrian

![Image](https://github.com/user-attachments/assets/fa679c81-eec3-449b-9838-09a04b7e6640)
![Image](https://github.com/user-attachments/assets/0829df5c-b1bb-4991-9294-9da2562493b6)

**Comment by Malcolm-Stewart** [comment]
It's a known bug in the tool and on the todo list.

**Comment by Malcolm-Stewart** [comment]
This is recently fixed. Will publish, tomorrow, most likely.
For SPN search purposes, converted the account from UPN format to NT format and it finds the SPNs okay.

Service Account:            sql2016svc@contoso.test
SPN Account:                CONTOSO\sql2016svc   <---------------------- new

    Suggested SPN                       Exists  Status             
    ----------------------------------  ------  -------------------
    MSSQLSvc/CON2016.CONTOSO.TEST:1433  True    Okay   <----------------- fixes the search
